version: '3'
services:
    zoo1:
        image: zookeeper
        restart: always
        volumes:
            - zoo1_conf:/conf
            - zoo1_data:/data
            - zoo1_datalog:/datalog
        ports:
          - 2181:2181
        environment:
            ZOO_MY_ID: 1
    solr1:
        image: solr
        restart: always
        ports:
            - 8983:8983
        volumes:
            - solr1_solr:/opt/solr/server/solr
            - solr1_logs:/opt/solr/server/logs
            - solr1_data:/var/solr
        environment:
            ZK_HOST: zoo1:2181
            SOLR_MODULES: sql
    solr2:
        image: solr
        restart: always
        ports:
            - 8984:8983
        volumes:
            - solr2_solr:/opt/solr/server/solr
            - solr2_logs:/opt/solr/server/logs
            - solr2_data:/var/solr
        environment:
            ZK_HOST: zoo1:2181
            SOLR_MODULES: sql

volumes:
    zoo1_conf:
    zoo1_data:
    zoo1_datalog:
    solr1_solr:
    solr1_logs:
    solr1_data:
    solr2_solr:
    solr2_logs:
    solr2_data:
