version: '3'
services:
    zoo1:
        image: zookeeper
        restart: always
        volumes:
            - zoo1:/conf
            - zoo1:/data
            - zoo1:/datalog
        ports:
          - 2181:2181
        environment:
            ZOO_MY_ID: 1
    solr1:
        image: solr
        restart: always
        ports:
            - 8983:8983
        volumes:
            - solr1:/opt/solr/server/solr
            - solr1:/opt/solr/server/logs
        environment:
            ZK_HOST: zoo1:2181
            SOLR_MODULES: sql
    solr2:
        image: solr
        restart: always
        ports:
            - 8984:8983
        volumes:
            - solr2:/opt/solr/server/solr
            - solr2:/opt/solr/server/logs
        environment:
            ZK_HOST: zoo1:2181
            SOLR_MODULES: sql
    solr3:
        image: solr
        restart: always
        ports:
            - 8985:8983
        volumes:
            - solr3:/opt/solr/server/solr
            - solr3:/opt/solr/server/logs
        environment:
            ZK_HOST: zoo1:2181
            SOLR_MODULES: sql            

volumes:
    zoo1:    
    solr1:
    solr2:
    solr3:
